version: '3.8'

services:
  mysql-springboot:
    restart: always
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myhotel_test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-prueba2
  app-sprint-boot:
    restart: always
    depends_on:
      - mysql-springboot
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-springboot:3306/myhotel_test?allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - springboot-mysql-prueba2
volumes:
  mysql_data:
  sprint-boot-prueba2:
networks:
  springboot-mysql-prueba2:
  